name: Calculate results

on:
  pull_request:

jobs:
  calculate:
    # Run scores updates only from forks.
    if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute
        run: |
          res=$(dotnet run coding-challange-399.csproj)
          timestamp=$(date +'%c')
          echo "${{ github.event.pull_request.base.user.login }}::$res::$timestamp" > score.txt
      - uses: actions/upload-artifact@v2
        with:
          name: score
          path: score.txt
          retention-days: 1