name: Calculate results

on:
  pull_request:

jobs:
  calculate:
    # Run scores updates only from forks.
    if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: jitterbit/get-changed-files@v1
        id: changes

      # Supported languages: cs (CSharp) and bash (Bash)
      - name: Get modified files
        id: language
        if: contains( steps.changes.outputs.modified, 'Program.cs' )
        run: |
          if [[ ${{ contains( steps.changes.outputs.modified, 'Program.cs' ) }} ]]; then
            echo "CSharp challenge"
            echo "::set-output name=lang::cs"
          elif [[ ${{ contains( steps.changes.outputs.modified, 'program.sh' ) }} ]]; then
            echo "Bash challenge"
            echo "::set-output name=lang::bash";
          fi

      - name: Get Current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%c')"

      # Require dotnet for CSharp challenges
      - uses: actions/setup-dotnet@v1
        if: steps.language.outputs.lang == 'cs'
        with:
          dotnet-version: '3.1.x'

      - name: Execute CSharp challenge
        if: steps.language.outputs.lang == 'cs'
        run: |
          dotnet build csharp
          res=$(dotnet run --project csharp/coding-challange-399.csproj)
          echo "Run result: $res"
          timestamp=${{ steps.timestamp.outputs.timestamp }}
          user=${{ github.event.pull_request.base.user.login }}
          echo "$user::$res::$timestamp" > score.txt

      # Bash challenges doesn't need any pre configuration
      - name: Execute Bash challenge
        if: steps.language.outputs.lang == 'bash'
        run: |
          res=$(./bash/program.sh)
          timestamp=${{ steps.timestamp.outputs.timestamp }}
          user=${{ github.event.pull_request.base.user.login }}
          echo "$user::$res::$timestamp" > score.txt

      - uses: actions/upload-artifact@v2
        with:
          name: score
          path: score.txt
          retention-days: 1
