name: Publish results

on:
  workflow_run:
    workflows: ["Calculate results"]
    branches: [main]
    types:
      - "completed"

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Download results from challenge submission
        uses: dawidd6/action-download-artifact@v2
        with:
          name: score
          workflow: calculate-results.yml

      - name: Update Github Pages
        run: |
          ls -l
          echo "::group::Create standings"
          echo "Score contents"
          cat score.txt
          cat score.txt >> dist/standings.txt
          echo "Standings contents"
          cat dist/standings.txt
          echo "::endgroup::"
          ls -l dist/
          cd dist
          git config --global user.email 'CI@example.com'
          git config --global user.name 'CI'
          git init
          git add -A
          git status
          git commit -m "build: publish challenge results ${{ github.run_number }}"
          git push -f https://Daniele-Tentoni:${{ github.token }}@github.com/Daniele-Tentoni/coding-challenge-399.git master:gh-pages
